/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ydCeRXBfSxk
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { Label } from "@/components/ui/label"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Card, CardHeader, CardContent, CardFooter } from "@/components/ui/card"
import React from "react"

export function MarketPlace() {
  return (
    <React.Fragment>
      <section className="bg-gray-100 dark:bg-gray-800 py-12 md:py-20">
        <div className="container px-4 md:px-6">
          <div className="grid md:grid-cols-2 gap-8 items-start">
            <div className="grid gap-4">
              <img
                src="/placeholder.svg"
                alt="Product Image"
                width={600}
                height={600}
                className="w-full rounded-lg object-cover"
                style={{ aspectRatio: "600/600", objectFit: "cover" }}
              />
              <div className="grid grid-cols-3 gap-4">
                <img
                  src="/placeholder.svg"
                  alt="Product Thumbnail"
                  width={100}
                  height={100}
                  className="w-full rounded-lg object-cover"
                  style={{ aspectRatio: "100/100", objectFit: "cover" }}
                />
                <img
                  src="/placeholder.svg"
                  alt="Product Thumbnail"
                  width={100}
                  height={100}
                  className="w-full rounded-lg object-cover"
                  style={{ aspectRatio: "100/100", objectFit: "cover" }}
                />
                <img
                  src="/placeholder.svg"
                  alt="Product Thumbnail"
                  width={100}
                  height={100}
                  className="w-full rounded-lg object-cover"
                  style={{ aspectRatio: "100/100", objectFit: "cover" }}
                />
              </div>
            </div>
            <div className="space-y-6">
              <div>
                <h1 className="text-3xl md:text-4xl font-bold">Wireless Headphones</h1>
                <p className="text-gray-500 dark:text-gray-400 text-lg">High-quality sound and comfortable fit.</p>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-3xl font-bold">$99.99</span>
                <div className="flex items-center gap-2">
                  <StarIcon className="w-5 h-5 fill-primary" />
                  <StarIcon className="w-5 h-5 fill-primary" />
                  <StarIcon className="w-5 h-5 fill-primary" />
                  <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                  <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                  <span className="text-sm text-gray-500 dark:text-gray-400">4.2 (23 reviews)</span>
                </div>
              </div>
              <form className="space-y-4">
                <div>
                  <Label htmlFor="color" className="text-base font-medium">
                    Color
                  </Label>
                  <RadioGroup id="color" defaultValue="black" className="flex items-center gap-2">
                    <Label
                      htmlFor="color-black"
                      className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                    >
                      <RadioGroupItem id="color-black" value="black" />
                      Black
                    </Label>
                    <Label
                      htmlFor="color-white"
                      className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                    >
                      <RadioGroupItem id="color-white" value="white" />
                      White
                    </Label>
                    <Label
                      htmlFor="color-blue"
                      className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                    >
                      <RadioGroupItem id="color-blue" value="blue" />
                      Blue
                    </Label>
                  </RadioGroup>
                </div>
                <div>
                  <Label htmlFor="size" className="text-base font-medium">
                    Size
                  </Label>
                  <RadioGroup id="size" defaultValue="m" className="flex items-center gap-2">
                    <Label
                      htmlFor="size-xs"
                      className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                    >
                      <RadioGroupItem id="size-xs" value="xs" />
                      XS
                    </Label>
                    <Label
                      htmlFor="size-s"
                      className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                    >
                      <RadioGroupItem id="size-s" value="s" />
                      S
                    </Label>
                    <Label
                      htmlFor="size-m"
                      className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                    >
                      <RadioGroupItem id="size-m" value="m" />
                      M
                    </Label>
                    <Label
                      htmlFor="size-l"
                      className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                    >
                      <RadioGroupItem id="size-l" value="l" />
                      L
                    </Label>
                    <Label
                      htmlFor="size-xl"
                      className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                    >
                      <RadioGroupItem id="size-xl" value="xl" />
                      XL
                    </Label>
                  </RadioGroup>
                </div>
                <div>
                  <Label htmlFor="quantity" className="text-base font-medium">
                    Quantity
                  </Label>
                  <Select defaultValue="1">
                    <SelectTrigger className="w-24">
                      <SelectValue placeholder="Select" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="1">1</SelectItem>
                      <SelectItem value="2">2</SelectItem>
                      <SelectItem value="3">3</SelectItem>
                      <SelectItem value="4">4</SelectItem>
                      <SelectItem value="5">5</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <Button size="lg">Add to Cart</Button>
              </form>
            </div>
          </div>
        </div>
      </section>
      <section className="py-12 md:py-20">
        <div className="container px-4 md:px-6">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-2xl md:text-3xl font-bold">Related Products</h2>
            <Link href="#" className="text-primary hover:underline" prefetch={false}>
              View all
            </Link>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            <div className="bg-white dark:bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition">
              <img
                src="/placeholder.svg"
                alt="Product Image"
                width={400}
                height={300}
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }}
              />
              <div className="p-4 space-y-2">
                <h3 className="text-lg font-semibold">Leather Backpack</h3>
                <p className="text-gray-500 dark:text-gray-400">Durable and stylish backpack for everyday use.</p>
                <div className="flex items-center justify-between">
                  <span className="text-2xl font-bold">$79.99</span>
                  <Button size="sm">Buy Now</Button>
                </div>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition">
              <img
                src="/placeholder.svg"
                alt="Product Image"
                width={400}
                height={300}
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }}
              />
              <div className="p-4 space-y-2">
                <h3 className="text-lg font-semibold">Smart Watch</h3>
                <p className="text-gray-500 dark:text-gray-400">Track your fitness and stay connected.</p>
                <div className="flex items-center justify-between">
                  <span className="text-2xl font-bold">$149.99</span>
                  <Button size="sm">Buy Now</Button>
                </div>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition">
              <img
                src="/placeholder.svg"
                alt="Product Image"
                width={400}
                height={300}
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }}
              />
              <div className="p-4 space-y-2">
                <h3 className="text-lg font-semibold">Outdoor Gear</h3>
                <p className="text-gray-500 dark:text-gray-400">High-quality equipment for your next adventure.</p>
                <div className="flex items-center justify-between">
                  <span className="text-2xl font-bold">$59.99</span>
                  <Button size="sm">Buy Now</Button>
                </div>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition">
              <img
                src="/placeholder.svg"
                alt="Product Image"
                width={400}
                height={300}
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }}
              />
              <div className="p-4 space-y-2">
                <h3 className="text-lg font-semibold">Wireless Headphones</h3>
                <p className="text-gray-500 dark:text-gray-400">High-quality sound and comfortable fit.</p>
                <div className="flex items-center justify-between">
                  <span className="text-2xl font-bold">$99.99</span>
                  <Button size="sm">Buy Now</Button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="py-12 md:py-20">
        <div className="container px-4 md:px-6">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-2xl md:text-3xl font-bold">Product Reviews</h2>
            <Link href="#" className="text-primary hover:underline" prefetch={false}>
              See all reviews
            </Link>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            <Card>
              <CardHeader className="flex flex-col items-center gap-4">
                <div className="bg-gray-100 px-3 py-2 rounded-full flex items-center dark:bg-gray-800">
                  <StarIcon className="w-5 h-5 fill-primary" />
                  <StarIcon className="w-5 h-5 fill-primary" />
                  <StarIcon className="w-5 h-5 fill-primary" />
                  <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                  <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                  <span className="text-sm ml-2 text-gray-500 dark:text-gray-400">4.2</span>
                </div>
                <div>
                  <h3 className="text-lg font-semibold">John Doe</h3>
                  <p className="text-gray-500 dark:text-gray-400 text-sm">Verified Buyer</p>
                </div>
              </CardHeader>
              <CardContent>
                <p className="text-gray-500 dark:text-gray-400">
                  "I absolutely love these headphones! The sound quality is amazing and they're so comfortable to wear.
                  Highly recommend!"
                </p>
              </CardContent>
              <CardFooter className="flex items-center justify-between">
                <div className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                  <ThumbsUpIcon className="w-4 h-4" />
                  <span>12 Helpful</span>
                </div>
                <div className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                  <CalendarIcon className="w-4 h-4" />
                  <span>2 days ago</span>
                </div>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader className="flex flex-col items-center gap-4">
                <div className="bg-gray-100 px-3 py-2 rounded-full flex items-center dark:bg-gray-800">
                  <StarIcon className="w-5 h-5 fill-primary" />
                  <StarIcon className="w-5 h-5 fill-primary" />
                  <StarIcon className="w-5 h-5 fill-primary" />
                  <StarIcon className="w-5 h-5 fill-primary" />
                  <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                  <span className="text-sm ml-2 text-gray-500 dark:text-gray-400">4.5</span>
                </div>
                <div>
                  <h3 className="text-lg font-semibold">Jane Smith</h3>
                  <p className="text-gray-500 dark:text-gray-400 text-sm">Verified Buyer</p>
                </div>
              </CardHeader>
              <CardContent>
                <p className="text-gray-500 dark:text-gray-400">
                  "I'm so impressed with these headphones! The noise cancellation is top-notch and the battery life is
                  incredible. Definitely worth the investment."
                </p>
              </CardContent>
              <CardFooter className="flex items-center justify-between">
                <div className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                  <ThumbsUpIcon className="w-4 h-4" />
                  <span>20 Helpful</span>
                </div>
                <div className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                  <CalendarIcon className="w-4 h-4" />
                  <span>1 week ago</span>
                </div>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader className="flex flex-col items-center gap-4">
                <div className="bg-gray-100 px-3 py-2 rounded-full flex items-center dark:bg-gray-800" />
              </CardHeader>
            </Card>
          </div>
        </div>
      </section>
    </React.Fragment>
  )
}

interface IconProps extends React.SVGProps<SVGSVGElement> {}

function CalendarIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


interface StarIconProps extends React.SVGProps<SVGSVGElement> {}

function StarIcon(props: StarIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


interface ThumbsUpIconProps extends React.SVGProps<SVGSVGElement> {}

function ThumbsUpIcon(props: ThumbsUpIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 10v12" />
      <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>
  )
}
